# xbrl-extraction - Playground

This notebook walks through the full public surface of the `xbrl_extraction` module.
Each section builds on the previous one. Run the **Imports** cell first, then work through the sections in order.

## 0 - Imports and paths

In [2]:
from pathlib import Path

from xbrl_extraction import (
    Document,
    # Entry points
    extract,
)

# Convenience paths - adjust if you add more filings
INPUT_ZIP  = Path("../data/input/rawdata_us_1860_1860_XBRL_2025-11-10.zip")
FACTS_JSON = Path(r"..\data\output\rawdata_us_1860_1860_XBRL_2025-11-10.json")

---
## 1 - Extraction from the source ZIP

`extract(zip_path)` parses the iXBRL filing end-to-end and returns an `ExtractionResult`.
The result bundles the `Document` (facts + schema) and all four linkbase objects together.

Fields on `ExtractionResult`:
- `.document` -> `Document` (facts, periods, units, filing metadata)
- `.calc` -> `Calculations`
- `.pres` -> `Presentation`
- `.labs` -> `Labels`
- `.defs` -> `Definitions`

> **Try:** call `extract(INPUT_ZIP)`, inspect `result.document.filing`, count facts.

In [3]:
result = extract(INPUT_ZIP)
print(result.document.filing)
print(f'Filing contains {len(result.document.facts)} facts.')

Filing(form='10-K', fiscal_year=2025, fiscal_period='FY', period_end='2025-09-27', accounting_standard='US-GAAP', source_file='rawdata_us_1860_1860_XBRL_2025-11-10.zip', primary_document='aapl-20250927.htm')
Filing contains 830 facts.

---
## 2 - Loading from pre-extracted JSON

If you have already run the CLI and have the `data/output/` files, you do not need to re-extract.
Two loading strategies:

### 2a - `Document.load(path)` - facts only
Loads the `.facts.json`. Linkbases are `None` until you attach them manually with `doc.attach_calc(path)`, `doc.attach_pres(path)`, etc. Good when you only need facts.

### 2b - `Document.load_all(path)` - facts + all siblings auto-attached
Loads the `.facts.json` and automatically discovers and attaches any sibling `.calc.json` / `.pres.json` / `.labs.json` / `.defs.json` in the same directory.

> **Try:** load with `Document.load_all(FACTS_JSON)`, then call `print(doc.summary())` to confirm all four linkbases are attached.

In [4]:
# Your code here
doc = Document.load(FACTS_JSON)
print(doc.facts)

[Fact(concept='aapl:AccruedDistributionAndMarketingCurrent', value=8919.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:AccruedDistributionAndMarketingCurrent', value=7679.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:CashCashEquivalentsAndMarketableSecurities', value=132420.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:CashCashEquivalentsAndMarketableSecurities', value=156650.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:CashCashEquivalentsAndMarketableSecuritiesCost', value=134711.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:CashCashEquivalentsAndMarketableSecuritiesCost', value=160600.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:CashEquivalentsAndMarketableSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', value=736.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:CashEquivalentsAndMarketableSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', value=688.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:CashEquivalentsAndMarketableSecuritiesAccumulatedGrossUnrealizedLossBeforeTax', value=3027.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:CashEquivalentsAndMarketableSecuritiesAccumulatedGrossUnrealizedLossBeforeTax', value=4638.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:DebtSecuritiesAvailableForSaleMaturityAllocatedAndSingleMaturityDateRollingAfterFiveThroughTenYearsPercentage', value=15.0, unit='number', period='c-89', decimals='2', scale='-2', dimensions={'us-gaap:FinancialInstrumentAxis': 'aapl:MarketableDebtSecuritiesOtherThanAssetBackedSecuritiesMember'}), Fact(concept='aapl:DebtSecuritiesAvailableForSaleMaturityAllocatedAndSingleMaturityDateRollingAfterFiveThroughTenYearsPercentage', value=14.0, unit='number', period='c-90', decimals='2', scale='-2', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:AssetBackedSecuritiesMember'}), Fact(concept='aapl:DebtSecuritiesAvailableForSaleMaturityAllocatedAndSingleMaturityDateRollingAfterOneThroughFiveYearsPercentage', value=80.0, unit='number', period='c-89', decimals='2', scale='-2', dimensions={'us-gaap:FinancialInstrumentAxis': 'aapl:MarketableDebtSecuritiesOtherThanAssetBackedSecuritiesMember'}), Fact(concept='aapl:DebtSecuritiesAvailableForSaleMaturityAllocatedAndSingleMaturityDateRollingAfterOneThroughFiveYearsPercentage', value=13.0, unit='number', period='c-90', decimals='2', scale='-2', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:AssetBackedSecuritiesMember'}), Fact(concept='aapl:DebtSecuritiesAvailableForSaleMaturityAllocatedAndSingleMaturityDateRollingAfterTenYearsPercentage', value=5.0, unit='number', period='c-89', decimals='2', scale='-2', dimensions={'us-gaap:FinancialInstrumentAxis': 'aapl:MarketableDebtSecuritiesOtherThanAssetBackedSecuritiesMember'}), Fact(concept='aapl:DebtSecuritiesAvailableForSaleMaturityAllocatedAndSingleMaturityDateRollingAfterTenYearsPercentage', value=73.0, unit='number', period='c-90', decimals='2', scale='-2', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:AssetBackedSecuritiesMember'}), Fact(concept='aapl:DeferredTaxAssetsCapitalizedResearchAndDevelopment', value=15041.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:DeferredTaxAssetsCapitalizedResearchAndDevelopment', value=10739.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:DeferredTaxAssetsLeaseLiabilities', value=2577.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:DeferredTaxAssetsLeaseLiabilities', value=2410.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:DeferredTaxLiabilitiesMinimumTaxonForeignEarnings', value=1217.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:DeferredTaxLiabilitiesMinimumTaxonForeignEarnings', value=1674.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:EffectiveIncomeTaxRateReconciliationImpactOfTheStateAidDecisionAmount', value=-486.0, unit='usd', period='c-1', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:EffectiveIncomeTaxRateReconciliationImpactOfTheStateAidDecisionAmount', value=10246.0, unit='usd', period='c-18', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:EquitySecuritiesFVNIAccumulatedGrossUnrealizedGainBeforeTax', value=177.0, unit='usd', period='c-64', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:MutualFundMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel1Member'}), Fact(concept='aapl:EquitySecuritiesFVNIAccumulatedGrossUnrealizedGainBeforeTax', value=177.0, unit='usd', period='c-65', decimals='-6', scale='6', dimensions={'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel1Member'}), Fact(concept='aapl:EquitySecuritiesFVNIAccumulatedGrossUnrealizedGainBeforeTax', value=105.0, unit='usd', period='c-77', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:MutualFundMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel1Member'}), Fact(concept='aapl:EquitySecuritiesFVNIAccumulatedGrossUnrealizedGainBeforeTax', value=105.0, unit='usd', period='c-78', decimals='-6', scale='6', dimensions={'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel1Member'}), Fact(concept='aapl:EquitySecuritiesFVNIAccumulatedGrossUnrealizedLossBeforeTax', value=2.0, unit='usd', period='c-64', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:MutualFundMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel1Member'}), Fact(concept='aapl:EquitySecuritiesFVNIAccumulatedGrossUnrealizedLossBeforeTax', value=2.0, unit='usd', period='c-65', decimals='-6', scale='6', dimensions={'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel1Member'}), Fact(concept='aapl:EquitySecuritiesFVNIAccumulatedGrossUnrealizedLossBeforeTax', value=3.0, unit='usd', period='c-77', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:MutualFundMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel1Member'}), Fact(concept='aapl:EquitySecuritiesFVNIAccumulatedGrossUnrealizedLossBeforeTax', value=3.0, unit='usd', period='c-78', decimals='-6', scale='6', dimensions={'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel1Member'}), Fact(concept='aapl:HedgeAccountingAdjustmentsRelatedToLongTermDebt', value=294.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:HedgeAccountingAdjustmentsRelatedToLongTermDebt', value=358.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:LesseeOperatingAndFinanceLeaseLiabilityToBePaid', value=16304.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:LesseeOperatingAndFinanceLeaseLiabilityToBePaidAfterYearFive', value=6757.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearFive', value=1424.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearFour', value=1633.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearOne', value=2530.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearThree', value=1899.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearTwo', value=2061.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:LesseeOperatingandFinanceLeaseLiabilityUndiscountedExcessAmount', value=2584.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:OperatingandFinanceLeaseLiability', value=13720.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:OperatingandFinanceLeaseLiability', value=12430.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:OperatingandFinanceLeaseRightofUseAsset', value=12238.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:OperatingandFinanceLeaseRightofUseAsset', value=11303.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:OperatingandFinanceLeaseWeightedAverageDiscountRatePercent', value=3.4, unit='number', period='c-20', decimals='3', scale='-2', dimensions={}), Fact(concept='aapl:OperatingandFinanceLeaseWeightedAverageDiscountRatePercent', value=3.1, unit='number', period='c-21', decimals='3', scale='-2', dimensions={}), Fact(concept='aapl:OtherComprehensiveIncomeLossDerivativeInstrumentGainLossReclassificationAfterTax', value=1337.0, unit='usd', period='c-18', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:OtherComprehensiveIncomeLossDerivativeInstrumentGainLossReclassificationAfterTax', value=1717.0, unit='usd', period='c-19', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:OtherComprehensiveIncomeLossDerivativeInstrumentGainLossafterReclassificationandTax', value=-2169.0, unit='usd', period='c-18', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:OtherComprehensiveIncomeLossDerivativeInstrumentGainLossafterReclassificationandTax', value=-1394.0, unit='usd', period='c-19', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:OtherComprehensiveIncomeLossDerivativeInstrumentGainLossbeforeReclassificationafterTax', value=-832.0, unit='usd', period='c-18', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:OtherComprehensiveIncomeLossDerivativeInstrumentGainLossbeforeReclassificationafterTax', value=323.0, unit='usd', period='c-19', decimals='-6', scale='6', dimensions={}), Fact(concept='aapl:RightofUseAssetsObtainedinExchangeforOperatingandFinanceLeaseLiabilities', value=2.8, unit='usd', period='c-1', decimals='-8', scale='9', dimensions={}), Fact(concept='aapl:RightofUseAssetsObtainedinExchangeforOperatingandFinanceLeaseLiabilities', value=1.0, unit='usd', period='c-18', decimals='-8', scale='9', dimensions={}), Fact(concept='aapl:RightofUseAssetsObtainedinExchangeforOperatingandFinanceLeaseLiabilities', value=2.1, unit='usd', period='c-19', decimals='-8', scale='9', dimensions={}), Fact(concept='aapl:StockIssuedDuringPeriodSharesSharebasedPaymentArrangementNetofSharesWithheldforTaxes', value=58146.0, unit='shares', period='c-138', decimals='-3', scale='3', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:CommonStockMember'}), Fact(concept='aapl:StockIssuedDuringPeriodSharesSharebasedPaymentArrangementNetofSharesWithheldforTaxes', value=66097.0, unit='shares', period='c-139', decimals='-3', scale='3', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:CommonStockMember'}), Fact(concept='aapl:StockIssuedDuringPeriodSharesSharebasedPaymentArrangementNetofSharesWithheldforTaxes', value=78055.0, unit='shares', period='c-140', decimals='-3', scale='3', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:CommonStockMember'}), Fact(concept='dei:EntityCommonStockSharesOutstanding', value=14776353000.0, unit='shares', period='c-11', decimals='-3', scale='0', dimensions={}), Fact(concept='dei:EntityPublicFloat', value=3253431000000.0, unit='usd', period='c-10', decimals='-6', scale='0', dimensions={}), Fact(concept='us-gaap:AccountsPayableCurrent', value=69860.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AccountsPayableCurrent', value=68960.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AccountsReceivableNetCurrent', value=39777.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AccountsReceivableNetCurrent', value=33410.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AccruedIncomeTaxesCurrent', value=13016.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AccruedIncomeTaxesCurrent', value=26601.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment', value=76014.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment', value=73448.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax', value=-5571.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax', value=-7172.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AdjustmentsRelatedToTaxWithholdingForShareBasedCompensation', value=4452.0, unit='usd', period='c-27', decimals='-6', scale='6', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:CommonStockIncludingAdditionalPaidInCapitalMember'}), Fact(concept='us-gaap:AdjustmentsRelatedToTaxWithholdingForShareBasedCompensation', value=3993.0, unit='usd', period='c-28', decimals='-6', scale='6', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:CommonStockIncludingAdditionalPaidInCapitalMember'}), Fact(concept='us-gaap:AdjustmentsRelatedToTaxWithholdingForShareBasedCompensation', value=3521.0, unit='usd', period='c-29', decimals='-6', scale='6', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:CommonStockIncludingAdditionalPaidInCapitalMember'}), Fact(concept='us-gaap:AdjustmentsRelatedToTaxWithholdingForShareBasedCompensation', value=1655.0, unit='usd', period='c-34', decimals='-6', scale='6', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:RetainedEarningsMember'}), Fact(concept='us-gaap:AdjustmentsRelatedToTaxWithholdingForShareBasedCompensation', value=1612.0, unit='usd', period='c-35', decimals='-6', scale='6', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:RetainedEarningsMember'}), Fact(concept='us-gaap:AdjustmentsRelatedToTaxWithholdingForShareBasedCompensation', value=2099.0, unit='usd', period='c-36', decimals='-6', scale='6', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:RetainedEarningsMember'}), Fact(concept='us-gaap:AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue', value=13246.0, unit='usd', period='c-27', decimals='-6', scale='6', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:CommonStockIncludingAdditionalPaidInCapitalMember'}), Fact(concept='us-gaap:AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue', value=12034.0, unit='usd', period='c-28', decimals='-6', scale='6', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:CommonStockIncludingAdditionalPaidInCapitalMember'}), Fact(concept='us-gaap:AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue', value=11138.0, unit='usd', period='c-29', decimals='-6', scale='6', dimensions={'us-gaap:StatementEquityComponentsAxis': 'us-gaap:CommonStockIncludingAdditionalPaidInCapitalMember'}), Fact(concept='us-gaap:AllocatedShareBasedCompensationExpense', value=12863.0, unit='usd', period='c-1', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AllocatedShareBasedCompensationExpense', value=11688.0, unit='usd', period='c-18', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AllocatedShareBasedCompensationExpense', value=10833.0, unit='usd', period='c-19', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount', value=24.0, unit='shares', period='c-61', decimals='-6', scale='6', dimensions={'us-gaap:AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareByAntidilutiveSecuritiesAxis': 'us-gaap:RestrictedStockUnitsRSUMember'}), Fact(concept='us-gaap:Assets', value=359241.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:Assets', value=364980.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AssetsCurrent', value=147957.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AssetsCurrent', value=152987.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AssetsNoncurrent', value=211284.0, unit='usd', period='c-20', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AssetsNoncurrent', value=211993.0, unit='usd', period='c-21', decimals='-6', scale='6', dimensions={}), Fact(concept='us-gaap:AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', value=56.0, unit='usd', period='c-66', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:USTreasurySecuritiesMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel2Member'}), Fact(concept='us-gaap:AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', value=111.0, unit='usd', period='c-68', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:ForeignGovernmentDebtSecuritiesMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel2Member'}), Fact(concept='us-gaap:AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', value=266.0, unit='usd', period='c-71', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:CorporateDebtSecuritiesMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel2Member'}), Fact(concept='us-gaap:AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', value=126.0, unit='usd', period='c-73', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:AssetBackedSecuritiesMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel2Member'}), Fact(concept='us-gaap:AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', value=559.0, unit='usd', period='c-74', decimals='-6', scale='6', dimensions={'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel2Member'}), Fact(concept='us-gaap:AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', value=45.0, unit='usd', period='c-79', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:USTreasurySecuritiesMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel2Member'}), Fact(concept='us-gaap:AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', value=93.0, unit='usd', period='c-81', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis': 'us-gaap:ForeignGovernmentDebtSecuritiesMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel2Member'}), Fact(concept='us-gaap:AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', value=270.0, unit='usd', period='c-84', decimals='-6', scale='6', dimensions={'us-gaap:FinancialInstrumentAxis'

In [26]:
doc = Document.load(r'C:\Users\AugustinHourquet\Documents\xbrl-extraction\data\output\rawdata_us_13091_13091_XBRL_2026-02-26.facts.json')
doc.attach_calc(r'C:\Users\AugustinHourquet\Documents\xbrl-extraction\data\output\rawdata_us_13091_13091_XBRL_2026-02-26.calc.json')
print(doc.summary())

10-K — FY2025 (US-GAAP)
  Source:    rawdata_us_13091_13091_XBRL_2026-02-26.zip
  Primary:   ande-20251231.htm
  Period end: 2025-12-31

Facts:  1264
  By namespace:
    us-gaap:                     1150
    ande:                        112
    dei:                         2
  By period type:
    duration                     693
    instant                      571
  Dimensional facts:           621 (49%)
  Top axes:
    us-gaap:StatementEquityComponentsAxis    97
    srt:ConsolidationItemsAxis               97
    us-gaap:DerivativeInstrumentRiskAxis     94
    us-gaap:StatementBusinessSegmentsAxis    83
    us-gaap:DebtInstrumentAxis               65

Attached linkbases:
  ✓ calc  (240 arcs across 23 roles)
  ✗ pres  (not attached)
  ✗ labs  (not attached)
  ✗ defs  (not attached)

In [27]:
doc = Document.load_all(FACTS_JSON)
print(doc.summary())

10-K — FY2025 (US-GAAP)
  Source:    rawdata_us_13091_13091_XBRL_2026-02-26.zip
  Primary:   ande-20251231.htm
  Period end: 2025-12-31

Facts:  1264
  By namespace:
    us-gaap:                     1150
    ande:                        112
    dei:                         2
  By period type:
    duration                     693
    instant                      571
  Dimensional facts:           621 (49%)
  Top axes:
    us-gaap:StatementEquityComponentsAxis    97
    srt:ConsolidationItemsAxis               97
    us-gaap:DerivativeInstrumentRiskAxis     94
    us-gaap:StatementBusinessSegmentsAxis    83
    us-gaap:DebtInstrumentAxis               65

Attached linkbases:
  ✓ calc  (240 arcs across 23 roles)
  ✓ pres  (1181 arcs, 105 statements)
  ✓ labs  (2062 labels)
  ✓ defs  (733 arcs)

---
## 3 - Exploring the Document

Once you have a `doc`, the core attributes are:

| Attribute | Type | What it holds |
|---|---|---|
| `doc.filing` | `Filing` | form, fiscal_year, period_end, accounting_standard, ... |
| `doc.facts` | `list[Fact]` | every numeric fact |
| `doc.periods` | `dict[str, Period]` | context_id -> Period (instant or duration) |
| `doc.units` | `dict[str, Unit]` | unit_id -> Unit (measure or numerator/denominator) |

Each `Fact` has: `.concept`, `.value`, `.unit`, `.period`, `.scale`, `.decimals`, `.dimensions`.

> **Try:** peek at `doc.facts[:5]`, inspect a single fact period via `doc.periods[fact.period]`, check `doc.filing.accounting_standard`.

In [ ]:
# Your code here
doc = Document.load_all(FACTS_JSON)
doc.units, doc.periods

({'usd': Unit(measure='iso4217:USD', numerator=None, denominator=None),
  't': Unit(measure='utr:T', numerator=None, denominator=None),
  'usdPerShare': Unit(measure=None, numerator='iso4217:USD', denominator='xbrli:shares'),
  'number': Unit(measure='xbrli:pure', numerator=None, denominator=None),
  'gal': Unit(measure='utr:gal', numerator=None, denominator=None),
  'shares': Unit(measure='xbrli:shares', numerator=None, denominator=None)},
 {'c-148': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-329': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-258': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-255': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-355': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-41': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-177': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-251': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-28': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-149': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-68': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-216': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-144': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-324': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-122': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-184': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-323': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-4': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-17': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-42': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-142': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-95': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-214': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-5': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-233': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-383': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-179': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-209': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-175': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-218': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-119': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-63': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-168': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-134': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-382': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-347': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-247': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-93': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-197': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-19': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-270': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-84': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-293': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-333': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-354': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-191': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-54': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-277': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-6': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-36': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-1': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-182': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-124': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-167': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-174': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-116': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-260': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-96': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-295': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-274': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-384': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-94': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-300': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-351': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-287': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-107': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-51': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-206': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-253': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-7': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-47': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-213': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-248': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-72': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-337': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-109': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-136': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-178': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-74': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-105': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-145': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-52': Period(type='instant', date='2025-07-31', start=None, end=None),
  'c-151': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-34': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-138': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-45': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-99': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-69': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-263': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-386': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-359': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-154': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-363': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-314': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-83': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-362': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-366': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-163': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-115': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-272': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-205': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-358': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-291': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-111': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-31': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-275': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-39': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-283': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-240': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-245': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-327': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-262': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-147': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-3': Period(type='instant', date='2026-02-06', start=None, end=None),
  'c-103': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-21': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-385': Period(type='instant', date='2022-12-31', start=None, end=None),
  'c-98': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-264': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-46': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-137': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-230': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-23': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-267': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-320': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-165': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-196': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-326': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-12': Period(type='instant', date='2022-12-31', start=None, end=None),
  'c-328': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-257': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-280': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-166': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-8': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-108': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-139': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-289': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-250': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-164': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-276': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-64': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-181': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-80': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-269': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-284': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-33': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-87': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-340': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-92': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-97': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-25': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-342': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-229': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-185': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-243': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-346': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-336': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-298': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-76': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-186': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-308': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-27': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-371': Period(type='duration', date=None, start='2023-04-18', end='2023-04-18'),
  'c-150': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-212': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-228': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-70': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-189': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-376': Period(type='duration', date=None, start='2025-01-01', end='2025-03-31'),
  'c-232': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-241': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-22': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-81': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-24': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-204': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-350': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-91': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-90': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-2': Period(type='instant', date='2025-06-30', start=None, end=None),
  'c-187': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-10': Period(type='instant', date='2022-12-31', start=None, end=None),
  'c-49': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-210': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-261': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-172': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-279': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-286': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-75': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-294': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-202': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-235': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-135': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-29': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-321': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-37': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-38': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-369': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-158': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-222': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-375': Period(type='instant', date='2024-01-31', start=None, end=None),
  'c-282': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-78': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-14': Period(type='instant', date='2022-12-31', start=None, end=None),
  'c-303': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-126': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-199': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-11': Period(type='instant', date='2022-12-31', start=None, end=None),
  'c-123': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-234': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-198': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-281': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-313': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-271': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-292': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-307': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-224': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-157': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-127': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-246': Period(type='instant', date='2023-12-31', start=None, end=None),
  'c-102': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-110': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-129': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-219': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-367': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-215': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-188': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-100': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-316': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-325': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-254': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'),
  'c-44': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-82': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-330': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-117': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-373': Period(type='instant', date='2023-04-18', start=None, end=None),
  'c-297': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-290': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-193': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-249': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-180': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-301': Period(type='duration', date=None, start='2023-01-01', end='2023-12-31'),
  'c-73': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-125': Period(type='instant', date='2025-12-31', start=None, end=None),
  'c-140': Period(type='instant', date='2024-12-31', start=None, end=None),
  'c-227': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'),
  'c-15': Period(type='instant', date='2022-12-31', start=None, end=None),
  'c-225': Period(type='instant', date='2023-12-31', start=None, end=None),

In [31]:
fact = doc.facts[1]
fact, doc.periods[fact.period], doc.filing.accounting_standard

(Fact(concept='ande:AccountsPayableTradeandOtherCurrent', value=1047436.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}),
 Period(type='instant', date='2024-12-31', start=None, end=None),
 'US-GAAP')

---
## 4 - Filtering facts

`doc.filter(**kwargs)` returns a **new** `Document` containing only facts that match every criterion. Filters AND together. The returned doc has its `periods` and `units` pruned to what is still referenced.

Available filter kwargs:

| kwarg | Description |
|---|---|
| `concept` | exact concept name, e.g. `"us-gaap:Assets"` |
| `concept_contains` | substring match (case-insensitive) |
| `concept_in` | list/set of concept names |
| `period` | exact context_id key |
| `period_end` | ISO date - matches any context ending on that date |
| `period_type` | `"instant"` or `"duration"` |
| `fiscal_year_only` | `True` - keeps only the full-year duration context |
| `unit` | exact unit_id |
| `currency` | `True` - keeps only `iso4217:` units |
| `no_dimensions` | `True` - drops all dimensional facts |
| `has_axis` | axis concept name must be present in dimensions |
| `has_member` | member concept name must be a value in dimensions |
| `statement` | `role_short` string (requires pres attached) |
| `statement_contains` | substring match on role_definition (requires pres) |
| `accounting_standard` | `"US-GAAP"` or `"IFRS"` |

> **Try:** filter to a specific concept, to duration facts only, or to a statement. Chain filters: `doc.filter(currency=True).filter(no_dimensions=True)`.

In [34]:
# Your code here
doc = Document.load_all(FACTS_JSON)
doc.filter(statement_contains = 'BALANCE')

Document(filing=Filing(form='10-K', fiscal_year=2025, fiscal_period='FY', period_end='2025-12-31', accounting_standard='US-GAAP', source_file='rawdata_us_13091_13091_XBRL_2026-02-26.zip', primary_document='ande-20251231.htm'), periods={'c-251': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-233': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-247': Period(type='duration', date=None, start='2025-01-01', end='2025-12-31'), 'c-333': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-277': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-6': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-36': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-295': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-274': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-7': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-47': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-213': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-248': Period(type='duration', date=None, start='2024-01-01', end='2024-12-31'), 'c-337': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-34': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-45': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-275': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-245': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-21': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-46': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-230': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-23': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-12': Period(type='instant', date='2022-12-31', start=None, end=None), 'c-280': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-8': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-250': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-276': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-33': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-340': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-25': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-229': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-336': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-212': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-228': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-22': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-24': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-10': Period(type='instant', date='2022-12-31', start=None, end=None), 'c-49': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-210': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-279': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-294': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-235': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-37': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-14': Period(type='instant', date='2022-12-31', start=None, end=None), 'c-11': Period(type='instant', date='2022-12-31', start=None, end=None), 'c-234': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-281': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-224': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-246': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-219': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-44': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-373': Period(type='instant', date='2023-04-18', start=None, end=None), 'c-249': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-15': Period(type='instant', date='2022-12-31', start=None, end=None), 'c-225': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-341': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-223': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-332': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-372': Period(type='instant', date='2023-04-18', start=None, end=None), 'c-26': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-48': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-13': Period(type='instant', date='2022-12-31', start=None, end=None), 'c-220': Period(type='instant', date='2023-12-31', start=None, end=None), 'c-273': Period(type='instant', date='2025-12-31', start=None, end=None), 'c-9': Period(type='instant', date='2022-12-31', start=None, end=None), 'c-35': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-32': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-211': Period(type='instant', date='2024-12-31', start=None, end=None), 'c-278': Period(type='instant', date='2023-12-31', start=None, end=None)}, units={'usd': Unit(measure='iso4217:USD', numerator=None, denominator=None), 'shares': Unit(measure='xbrli:shares', numerator=None, denominator=None)}, facts=[Fact(concept='ande:AccountsPayableTradeandOtherCurrent', value=918691.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='ande:AccountsPayableTradeandOtherCurrent', value=1047436.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='ande:FairValueMeasurementwithUnobservableInputsReconciliationRecurringBasisAssetNewAgreements', value=4000.0, unit='usd', period='c-247', decimals='-3', scale='3', dimensions={'us-gaap:FairValueByAssetClassAxis': 'us-gaap:ConvertiblePreferredStockMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel3Member'}), Fact(concept='ande:FairValueMeasurementwithUnobservableInputsReconciliationRecurringBasisAssetNewAgreements', value=100.0, unit='usd', period='c-248', decimals='-3', scale='3', dimensions={'us-gaap:FairValueByAssetClassAxis': 'us-gaap:ConvertiblePreferredStockMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel3Member'}), Fact(concept='ande:LeaseLiability', value=108222.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='ande:LeaseLiability', value=102585.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='ande:RightofUseAsset', value=130051.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='ande:RightofUseAsset', value=127749.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AccountsNotesAndLoansReceivableNetCurrent', value=9.6, unit='usd', period='c-372', decimals='-5', scale='6', dimensions={'us-gaap:RelatedPartyTransactionsByRelatedPartyAxis': 'us-gaap:RelatedPartyMember', 'srt:CounterpartyNameAxis': 'ande:ElementLLCMember', 'us-gaap:AccountsNotesLoansAndFinancingReceivableByReceivableTypeAxis': 'ande:RawMaterialAndFeesReceivableMember'}), Fact(concept='us-gaap:AccountsNotesAndLoansReceivableNetCurrent', value=2.0, unit='usd', period='c-373', decimals='-5', scale='6', dimensions={'us-gaap:RelatedPartyTransactionsByRelatedPartyAxis': 'us-gaap:RelatedPartyMember', 'srt:CounterpartyNameAxis': 'ande:ElementLLCMember', 'us-gaap:AccountsNotesLoansAndFinancingReceivableByReceivableTypeAxis': 'ande:LoansAndInterestDueMember'}), Fact(concept='us-gaap:AccountsNotesAndLoansReceivableNetCurrent', value=652472.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AccountsNotesAndLoansReceivableNetCurrent', value=764550.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AccruedLiabilitiesCurrent', value=208427.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AccruedLiabilitiesCurrent', value=227192.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax', value=11337.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax', value=12585.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AdditionalPaidInCapitalCommonStock', value=208425.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AdditionalPaidInCapitalCommonStock', value=385609.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AllowanceForDoubtfulAccountsReceivableCurrent', value=42554.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AllowanceForDoubtfulAccountsReceivableCurrent', value=48325.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:Assets', value=2847954.0, unit='usd', period='c-273', decimals='-3', scale='3', dimensions={'srt:ConsolidationItemsAxis': 'us-gaap:OperatingSegmentsMember', 'us-gaap:StatementBusinessSegmentsAxis': 'ande:AgribusinessSegmentMember'}), Fact(concept='us-gaap:Assets', value=2778025.0, unit='usd', period='c-274', decimals='-3', scale='3', dimensions={'srt:ConsolidationItemsAxis': 'us-gaap:OperatingSegmentsMember', 'us-gaap:StatementBusinessSegmentsAxis': 'ande:AgribusinessSegmentMember'}), Fact(concept='us-gaap:Assets', value=2581977.0, unit='usd', period='c-275', decimals='-3', scale='3', dimensions={'srt:ConsolidationItemsAxis': 'us-gaap:OperatingSegmentsMember', 'us-gaap:StatementBusinessSegmentsAxis': 'ande:AgribusinessSegmentMember'}), Fact(concept='us-gaap:Assets', value=617253.0, unit='usd', period='c-276', decimals='-3', scale='3', dimensions={'srt:ConsolidationItemsAxis': 'us-gaap:OperatingSegmentsMember', 'us-gaap:StatementBusinessSegmentsAxis': 'ande:RenewablesSegmentMember'}), Fact(concept='us-gaap:Assets', value=680546.0, unit='usd', period='c-277', decimals='-3', scale='3', dimensions={'srt:ConsolidationItemsAxis': 'us-gaap:OperatingSegmentsMember', 'us-gaap:StatementBusinessSegmentsAxis': 'ande:RenewablesSegmentMember'}), Fact(concept='us-gaap:Assets', value=780477.0, unit='usd', period='c-278', decimals='-3', scale='3', dimensions={'srt:ConsolidationItemsAxis': 'us-gaap:OperatingSegmentsMember', 'us-gaap:StatementBusinessSegmentsAxis': 'ande:RenewablesSegmentMember'}), Fact(concept='us-gaap:Assets', value=247625.0, unit='usd', period='c-279', decimals='-3', scale='3', dimensions={'srt:ConsolidationItemsAxis': 'us-gaap:MaterialReconcilingItemsMember'}), Fact(concept='us-gaap:Assets', value=662743.0, unit='usd', period='c-280', decimals='-3', scale='3', dimensions={'srt:ConsolidationItemsAxis': 'us-gaap:MaterialReconcilingItemsMember'}), Fact(concept='us-gaap:Assets', value=492553.0, unit='usd', period='c-281', decimals='-3', scale='3', dimensions={'srt:ConsolidationItemsAxis': 'us-gaap:MaterialReconcilingItemsMember'}), Fact(concept='us-gaap:Assets', value=47.8, unit='usd', period='c-294', decimals='-5', scale='6', dimensions={'srt:StatementGeographicalAxis': 'country:CA'}), Fact(concept='us-gaap:Assets', value=45.8, unit='usd', period='c-295', decimals='-5', scale='6', dimensions={'srt:StatementGeographicalAxis': 'country:CA'}), Fact(concept='us-gaap:Assets', value=3712832.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:Assets', value=4121314.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:Assets', value=3855007.0, unit='usd', period='c-8', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AssetsCurrent', value=2376409.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:AssetsCurrent', value=2850277.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:CashAndCashEquivalentsAtCarryingValue', value=98283.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:CashAndCashEquivalentsAtCarryingValue', value=561771.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:CommodityContractAssetCurrent', value=135466.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:CommodityContractAssetCurrent', value=148801.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:CommonStockSharesAuthorized', value=63000.0, unit='shares', period='c-6', decimals='INF', scale='3', dimensions={}), Fact(concept='us-gaap:CommonStockSharesAuthorized', value=63000.0, unit='shares', period='c-7', decimals='INF', scale='3', dimensions={}), Fact(concept='us-gaap:CommonStockSharesIssued', value=34211.0, unit='shares', period='c-6', decimals='INF', scale='3', dimensions={}), Fact(concept='us-gaap:CommonStockSharesIssued', value=34083.0, unit='shares', period='c-7', decimals='INF', scale='3', dimensions={}), Fact(concept='us-gaap:CommonStockValue', value=144.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:CommonStockValue', value=142.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:ContractWithCustomerLiabilityCurrent', value=195331.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:ContractWithCustomerLiabilityCurrent', value=194025.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:DeferredIncomeTaxLiabilities', value=14208.0, unit='usd', period='c-212', decimals='-3', scale='3', dimensions={'us-gaap:BalanceSheetLocationAxis': 'us-gaap:OtherNoncurrentLiabilitiesMember'}), Fact(concept='us-gaap:DeferredIncomeTaxLiabilities', value=55005.0, unit='usd', period='c-213', decimals='-3', scale='3', dimensions={'us-gaap:BalanceSheetLocationAxis': 'us-gaap:OtherNoncurrentLiabilitiesMember'}), Fact(concept='us-gaap:DeferredIncomeTaxLiabilities', value=60143.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:DeferredIncomeTaxLiabilities', value=117740.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:DeferredTaxAssetsLiabilitiesNet', value=16426.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:DeferredTaxAssetsNet', value=30634.0, unit='usd', period='c-210', decimals='-3', scale='3', dimensions={'us-gaap:BalanceSheetLocationAxis': 'us-gaap:OtherNoncurrentAssetsMember'}), Fact(concept='us-gaap:DeferredTaxAssetsNet', value=1632.0, unit='usd', period='c-211', decimals='-3', scale='3', dimensions={'us-gaap:BalanceSheetLocationAxis': 'us-gaap:OtherNoncurrentAssetsMember'}), Fact(concept='us-gaap:DeferredTaxAssetsNet', value=76569.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:DeferredTaxAssetsNet', value=64367.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:DeferredTaxLiabilities', value=53373.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:DerivativeLiabilitiesCurrent', value=51153.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:DerivativeLiabilitiesCurrent', value=59766.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetGainLossIncludedInEarnings1', value=-1535.0, unit='usd', period='c-248', decimals='-3', scale='3', dimensions={'us-gaap:FairValueByAssetClassAxis': 'us-gaap:ConvertiblePreferredStockMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel3Member'}), Fact(concept='us-gaap:FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetValue', value=14190.0, unit='usd', period='c-245', decimals='-3', scale='3', dimensions={'us-gaap:FairValueByAssetClassAxis': 'us-gaap:ConvertiblePreferredStockMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel3Member'}), Fact(concept='us-gaap:FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetValue', value=15625.0, unit='usd', period='c-246', decimals='-3', scale='3', dimensions={'us-gaap:FairValueByAssetClassAxis': 'us-gaap:ConvertiblePreferredStockMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel3Member'}), Fact(concept='us-gaap:FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetValue', value=18190.0, unit='usd', period='c-249', decimals='-3', scale='3', dimensions={'us-gaap:FairValueByAssetClassAxis': 'us-gaap:ConvertiblePreferredStockMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel3Member'}), Fact(concept='us-gaap:FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetValue', value=18190.0, unit='usd', period='c-250', decimals='-3', scale='3', dimensions={'us-gaap:FairValueByAssetClassAxis': 'us-gaap:ConvertiblePreferredStockMember', 'us-gaap:FairValueByMeasurementFrequencyAxis': 'us-gaap:FairValueMeasurementsRecurringMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel3Member', 'us-gaap:ValuationTechniqueAxis': 'us-gaap:MarketApproachValuationTechniqueMember'}), Fact(concept='us-gaap:FairValueMeasurementWithUnobservableInputsReconciliationRecurringBasisAssetValue', value=14190.0, unit='usd', period='c-251', decimals='-3', scale='3', dimensions={'us-gaap:FairValueByAssetClassAxis': 'us-gaap:ConvertiblePreferredStockMember', 'us-gaap:FairValueByMeasurementFrequencyAxis': 'us-gaap:FairValueMeasurementsRecurringMember', 'us-gaap:FairValueByFairValueHierarchyLevelAxis': 'us-gaap:FairValueInputsLevel3Member', 'us-gaap:ValuationTechniqueAxis': 'us-gaap:MarketApproachValuationTechniqueMember'}), Fact(concept='us-gaap:FinanceLeaseLiability', value=9596.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:FinanceLeaseLiability', value=11500.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:FinanceLeaseLiabilityCurrent', value=2037.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:FinanceLeaseLiabilityCurrent', value=1884.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:FinanceLeaseLiabilityNoncurrent', value=7559.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:FinanceLeaseLiabilityNoncurrent', value=9616.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:FinanceLeaseRightOfUseAsset', value=21259.0, unit='usd', period='c-6', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:FinanceLeaseRightOfUseAsset', value=23119.0, unit='usd', period='c-7', decimals='-3', scale='3', dimensions={}), Fact(concept='us-gaap:Goodwill', value=119067.0, unit='usd', period='c-332', decimals='-3', scale='3', dimensions={'us-gaap:StatementBusinessSegmentsAxis': 'ande:AgribusinessSegmentMember'}), Fact(concept='us-gaap:Goodwill', value=8789.0, unit='usd', period='c-333', decimals='-3', scale='3', dimensions={'us-gaap:StatementBusinessSegmentsAxis': 'ande:RenewablesSegmentMember'}), Fact(concept='us-gaap:Goodwill', value=119067.0, unit='usd', period='c-336', decimals='-3', scale='3', dimensions={'us-gaap:StatementBusinessSegmentsAxis': 'ande:AgribusinessSegmentMember'}), Fact(concept='us-gaap:Goodwill', value=8789.0, uni

---
## 5 - Exporting to a DataFrame

`doc.to_dataframe()` flattens all facts into a long-format pandas DataFrame. Periods and units are denormalised into per-row columns. If labels are attached, a `label` column is added.

Resulting columns: `concept`, `value`, `unit`, `unit_measure`, `period`, `period_type`, `period_start`, `period_end`, `period_date`, `scale`, `decimals`, `dimensions`, `source_file`, (`label` if labs attached).

> **Try:** call `doc.to_dataframe()`, then filter/group in pandas - e.g. group by `concept` to see all reported values for a given line item across periods.

In [ ]:
# Your code here
doc = Document.load_all(FACTS_JSON)
df = doc.filter(statement_contains = "BALANCE").to_dataframe()
df.groupby("unit").first()

,concept,value,unit_measure,period,period_type,period_start,period_end,period_date,scale,decimals,dimensions,source_file,label
unit,,,,,,,,,,,,,
shares,us-gaap:CommonStockSharesAuthorized,63000.0,xbrli:shares,c-6,instant,NaN,NaN,2025-12-31,3,INF,None,rawdata_us_13091_13091_XBRL_2026-02-26.zip,"Common Stock, Shares Authorized"
usd,ande:AccountsPayableTradeandOtherCurrent,918691.0,iso4217:USD,c-6,instant,2025-01-01,2025-12-31,2025-12-31,3,-3,{'us-gaap:FairValueByAssetClassAxis': 'us-gaap...,rawdata_us_13091_13091_XBRL_2026-02-26.zip,"Accounts Payable, Trade and Other, Current"

---
## 6 - Calc linkbase - graph navigation

Requires `doc.calc` to be attached (it is after `load_all`).

### Available statements
Get the list of calc roles from `doc.calc.role_definitions` (a `dict[role_short, label]`).

### Navigation methods

| Method | Returns | Description |
|---|---|---|
| `doc.children_of(concept, role_short=None)` | `list[dict]` | Direct children in the calc graph. Each dict: `concept`, `weight`, `order`, `role`. |
| `doc.parent_of(concept, role_short=None)` | `list[dict]` | Direct parents. Each dict: `concept`, `weight`, `role`. |
| `doc.tree(role_short)` | `dict` | Full nested dict of the calc tree for one role. Root -> children -> grandchildren. |
| `doc.expand(concept, role_short, period_end)` | `DataFrame` | Walk a subtree and join actual fact values. Columns: `concept`, `depth`, `weight_path`, `value`, `label`. |

> **Try:** list `doc.calc.role_definitions`, pick a role, call `doc.tree(role_short)`, then `doc.expand(root_concept, role_short, doc.filing.period_end)`.

In [ ]:
# Your code here
doc = Document.load_all(FACTS_JSON)

for role in doc.calc.role_definitions:
    if doc.calc.role_definitions[role] == "Property, Plant and Equipment":
        print(f'{role}: {doc.calc.role_definitions[role]}' )

doc.children_of(concept = 'us-gaap:Assets'), doc.parent_of('us-gaap:PropertyPlantAndEquipmentNet')

http://www.andersonsinc.com/role/Cover: Cover
http://www.andersonsinc.com/role/AuditInformation: Audit Information
http://www.andersonsinc.com/role/ConsolidatedStatementsofOperations: Consolidated Statements of Operations
http://www.andersonsinc.com/role/ConsolidatedStatementsofComprehensiveIncome: Consolidated Statements of Comprehensive Income
http://www.andersonsinc.com/role/ConsolidatedBalanceSheets: Consolidated Balance Sheets
http://www.andersonsinc.com/role/ConsolidatedBalanceSheetsParenthetical: Consolidated Balance Sheets (Parenthetical)
http://www.andersonsinc.com/role/ConsolidatedStatementsofCashFlows: Consolidated Statements of Cash Flows
http://www.andersonsinc.com/role/ConsolidatedStatementsofEquity: Consolidated Statements of Equity
http://www.andersonsinc.com/role/ConsolidatedStatementsofEquityParenthetical: Consolidated Statements of Equity (Parenthetical)
http://www.andersonsinc.com/role/SummaryofSignificantAccountingPolicies: Summary of Significant Accounting Policies
http://www.andersonsinc.com/role/Inventories: Inventories
http://www.andersonsinc.com/role/PropertyPlantandEquipment: Property, Plant and Equipment
http://www.andersonsinc.com/role/Debt: Debt
http://www.andersonsinc.com/role/Derivatives: Derivatives
http://www.andersonsinc.com/role/Revenue: Revenue
http://www.andersonsinc.com/role/IncomeTaxes: Income Taxes
http://www.andersonsinc.com/role/AccumulatedOtherComprehensiveIncomeLoss: Accumulated Other Comprehensive Income (Loss)
http://www.andersonsinc.com/role/FairValueMeasurements: Fair Value Measurements
http://www.andersonsinc.com/role/SegmentInformation: Segment Information
http://www.andersonsinc.com/role/Leases: Leases
http://www.andersonsinc.com/role/CommitmentsandContingencies: Commitments and Contingencies
http://www.andersonsinc.com/role/StockCompensationPlans: Stock Compensation Plans
http://www.andersonsinc.com/role/GoodwillandOtherIntangibleAssets: Goodwill and Other Intangible Assets
http://www.andersonsinc.com/role/OtherIncomeNet: Other Income, Net
http://www.andersonsinc.com/role/EarningsPerShare: Earnings Per Share
http://www.andersonsinc.com/role/ELEMENT: ELEMENT
http://www.andersonsinc.com/role/BusinessAcquisition: Business Acquisition
http://www.andersonsinc.com/role/ScheduleIIConsolidatedValuationandQualifyingAccounts: Consolidated Valuation and Qualifying Accounts
http://www.andersonsinc.com/role/SummaryofSignificantAccountingPoliciesPolicies: Summary of Significant Accounting Policies (Policies)
http://www.andersonsinc.com/role/InventoriesTables: Inventories (Tables)
http://www.andersonsinc.com/role/PropertyPlantandEquipmentTables: Property, Plant and Equipment (Tables)
http://www.andersonsinc.com/role/DebtTables: Debt (Tables)
http://www.andersonsinc.com/role/DerivativesTables: Derivatives (Tables)
http://www.andersonsinc.com/role/RevenueTables: Revenue (Tables)
http://www.andersonsinc.com/role/IncomeTaxesTables: Income Taxes (Tables)
http://www.andersonsinc.com/role/AccumulatedOtherComprehensiveIncomeLossTables: Accumulated Other Comprehensive Income (Loss) (Tables)
http://www.andersonsinc.com/role/FairValueMeasurementsTables: Fair Value Measurements (Tables)
http://www.andersonsinc.com/role/SegmentInformationTables: Segment Information (Tables)
http://www.andersonsinc.com/role/LeasesTables: Leases (Tables)
http://www.andersonsinc.com/role/StockCompensationPlansTables: Stock Compensation Plans (Tables)
http://www.andersonsinc.com/role/GoodwillandOtherIntangibleAssetsTable: Goodwill and Other Intangible Assets (Table)
http://www.andersonsinc.com/role/OtherIncomeNetTables: Other Income, Net (Tables)
http://www.andersonsinc.com/role/EarningsPerShareTables: Earnings Per Share (Tables)
http://www.andersonsinc.com/role/BusinessAcquisitionTables: Business Acquisition (Tables)
http://www.andersonsinc.com/role/SummaryofSignificantAccountingPoliciesDetails: Summary of Significant Accounting Policies (Details)
http://www.andersonsinc.com/role/InventoriesDetails: Inventories (Details)
http://www.andersonsinc.com/role/PropertyPlantandEquipmentDetails: Property, Plant and Equipment (Details)
http://www.andersonsinc.com/role/DebtTextualDetails: Debt (Textual) (Details)
http://www.andersonsinc.com/role/DebtLongtermdebtDetails: Debt (Long-term debt) (Details)
http://www.andersonsinc.com/role/DerivativesTextualDetails: Derivatives (Textual) (Details)
http://www.andersonsinc.com/role/DerivativesFairValueofCommodityDerivativeswithCashCollateralDetails: Derivatives (Fair Value of Commodity Derivatives with Cash Collateral) (Details)
http://www.andersonsinc.com/role/DerivativesCurrentandNoncurrentDerivativeAssetsDetails: Derivatives (Current and Noncurrent Derivative Assets) (Details)
http://www.andersonsinc.com/role/DerivativesDerivativesGainsandLossesDetails: Derivatives (Derivatives Gains and Losses) (Details)
http://www.andersonsinc.com/role/DerivativesCommodityDerivativeContractsOutstandingDetails: Derivatives (Commodity Derivative Contracts Outstanding) (Details)
http://www.andersonsinc.com/role/DerivativesFairValueofCompanysOtherDerivativesDetails: Derivatives (Fair Value of Company's Other Derivatives) (Details)
http://www.andersonsinc.com/role/DerivativesInterestRateGainsLossesDetails: Derivatives (Interest Rate Gains (Losses)) (Details)
http://www.andersonsinc.com/role/DerivativesScheduleofOpenInterestRateContractsDetails: Derivatives (Schedule of Open Interest Rate Contracts) (Details)
http://www.andersonsinc.com/role/RevenueDisaggregationofRevenuesDetails: Revenue (Disaggregation of Revenues) (Details)
http://www.andersonsinc.com/role/RevenueTextualDetails: Revenue (Textual) (Details)
http://www.andersonsinc.com/role/IncomeTaxesIncomeTaxProvisionDetails: Income Taxes (Income Tax Provision) (Details)
http://www.andersonsinc.com/role/IncomeTaxesIncomeLossBeforeIncomeTaxesfromContinuingOperationsDetails: Income Taxes (Income (Loss) Before Income Taxes from Continuing Operations) (Details)
http://www.andersonsinc.com/role/IncomeTaxesEffectiveIncomeTaxReconciliationDetails: Income Taxes (Effective Income Tax Reconciliation) (Details)
http://www.andersonsinc.com/role/IncomeTaxesScheduleofIncomeTaxesPaidDetails: Income Taxes (Schedule of Income Taxes Paid) (Details)
http://www.andersonsinc.com/role/IncomeTaxesTextualDetails: Income Taxes (Textual) (Details)
http://www.andersonsinc.com/role/IncomeTaxesComponentsofDeferredTaxAssetsandLiabilitiesDetails: Income Taxes (Components of Deferred Tax Assets and Liabilities) (Details)
http://www.andersonsinc.com/role/IncomeTaxesDeferredTaxesRecognizedinBalanceSheetDetails: Income Taxes (Deferred Taxes Recognized in Balance Sheet) (Details)
http://www.andersonsinc.com/role/IncomeTaxesReconciliationofUnrecognizedTaxBenefitsDetails: Income Taxes (Reconciliation of Unrecognized Tax Benefits) (Details)
http://www.andersonsinc.com/role/AccumulatedOtherComprehensiveIncomeLossDetails: Accumulated Other Comprehensive Income (Loss) (Details)
http://www.andersonsinc.com/role/FairValueMeasurementsAssetsandLiabilitiesMeasuredatFairValueonaRecurringBasisDetails: Fair Value Measurements (Assets and Liabilities Measured at Fair Value on a Recurring Basis) (Details)
http://www.andersonsinc.com/role/FairValueMeasurementsReconciliationofEndingBalancesofRecurringFairValueMeasurementsUsingLevel3InputsDetails: Fair Value Measurements (Reconciliation of Ending Balances of Recurring Fair Value Measurements Using Level 3 Inputs) (Details)
http://www.andersonsinc.com/role/FairValueMeasurementsSummarizedInformationAboutLevel3FairValueMeasurementsDetails: Fair Value Measurements (Summarized Information About Level 3 Fair Value Measurements) (Details)
http://www.andersonsinc.com/role/FairValueMeasurementsAdditionalInformationDetails: Fair Value Measurements (Additional Information) (Details)
http://www.andersonsinc.com/role/SegmentInformationAdditionalInformationDetails: Additional Information (Details)
http://www.andersonsinc.com/role/SegmentInformationSegmentInformationDetails: Segment Information (Details)
http://www.andersonsinc.com/role/SegmentInformationIdentifiableAssetsbySegmentDetails: Identifiable Assets by Segment (Details)
http://www.andersonsinc.com/role/SegmentInformationSegmentInformationbyGeographicRegionDetails: Segment Information by Geographic Region (Details)
http://www.andersonsinc.com/role/LeasesComponentsofLeaseCostDetails: Leases (Components of Lease Cost) (Details)
http://www.andersonsinc.com/role/LeasesSupplementalCashFlowInformationDetails: Leases (Supplemental Cash Flow Information) (Details)
http://www.andersonsinc.com/role/LeasesSummaryofAmountsRecognizedinCondensedConsolidatedBalanceSheetDetails: Leases (Summary of Amounts Recognized in Condensed Consolidated Balance Sheet) (Details)
http://www.andersonsinc.com/role/LeasesWeightedAverageRemainingLeaseTermDetails: Leases (Weighted Average Remaining Lease Term) (Details)
http://www.andersonsinc.com/role/LeasesWeightedAverageDiscountRateDetails: Leases (Weighted Average Discount Rate) (Details)
http://www.andersonsinc.com/role/LeasesMaturityAnalysisofLeaseLiabilitiesDetails: Leases (Maturity Analysis of Lease Liabilities) (Details)
http://www.andersonsinc.com/role/LeasesMaturityAnalysisofLeaseLiabilitiesDetails_1: Leases (Maturity Analysis of Lease Liabilities) (Details)
http://www.andersonsinc.com/role/StockCompensationPlansAdditionalInformationDetails: Stock Compensation Plans (Additional Information) (Details)
http://www.andersonsinc.com/role/StockCompensationPlansStockCompensationExpenseandRelatedIncomeTaxImpactsDetails: Stock Compensation Plans (Stock Compensation Expense and Related Income Tax Impacts) (Details)
http://www.andersonsinc.com/role/StockCompensationPlansRestrictedStockAwardsDetails: Stock Compensation Plans (Restricted Stock Awards) (Details)
http://www.andersonsinc.com/role/StockCompensationPlansModifiedPSUsDetails: Stock Compensation Plans (Modified PSUs) (Details)
http://www.andersonsinc.com/role/StockCompensationPlansEPSPSUsActivityDetails: Stock Compensation Plans (EPS PSUs Activity) (Details)
http://www.andersonsinc.com/role/StockCompensationPlansTSRPSUsActivityDetails: Stock Compensation Plans (TSR PSUs Activity) (Details)
http://www.andersonsinc.com/role/StockCompensationPlansEmployeeSharePurchasePlanDetails: Stock Compensation Plans (Employee Share Purchase Plan) (Details)
http://www.andersonsinc.com/role/StockCompensationPlansWeightedAverageAssumptionsUsedtoDetermineFairValueofESPPlanDetails: Stock Compensation Plans (Weighted Average Assumptions Used to Determine Fair Value of ESP Plan) (Details)
http://www.andersonsinc.com/role/GoodwillandOtherIntangibleAssetsChangesinGoodwillDetails: Goodwill and Other Intangible Assets (Changes in Goodwill) (Details)
http://www.andersonsinc.com/role/GoodwillandOtherIntangibleAssetsTextualDetails: Goodwill and Other Intangible Assets (Textual) (Details)
http://www.andersonsinc.com/role/GoodwillandOtherIntangibleAssetsIntangibleAssetsDetails: Goodwill and Other Intangible Assets (Intangible Assets) (Details)
http://www.andersonsinc.com/role/OtherIncomeNetItemsinOtherIncomeDetails: Other Income, Net (Items in Other Income) (Details)
http://www.andersonsinc.com/role/OtherIncomeNetNarrativeDetails: Other Income, Net (Narrative) (Details)
http://www.andersonsinc.com/role/EarningsPerShareDetails: Earnings Per Share (Details)
http://www.andersonsinc.com/role/ELEMENTDetails: ELEMENT (Details)
http://www.andersonsinc.com/role/BusinessAcquisitionAdditionalInformationDetails: Business Acquisition (Additional Information) (Details)
http://www.andersonsinc.com/role/BusinessAcquisitionPurchasePriceAllocationDetails: Business Acquisition (Purchase Price Allocation) (Details)
http://www.andersonsinc.com/role/ScheduleIIConsolidatedValuationandQualifyingAccountsDetails: Consolidated Valuation and Qualifying Accounts (Details)

([{'concept': 'us-gaap:InvestmentsAndOtherNoncurrentAssets',
   'weight': 1.0,
   'order': 1.0,
   'role': 'ConsolidatedBalanceSheets'},
  {'concept': 'us-gaap:PropertyPlantAndEquipmentNet',
   'weight': 1.0,
   'order': 2.0,
   'role': 'ConsolidatedBalanceSheets'},
  {'concept': 'us-gaap:AssetsCurrent',
   'weight': 1.0,
   'order': 3.0,
   'role': 'ConsolidatedBalanceSheets'}],
 [{'concept': 'us-gaap:Assets',
   'weight': 1.0,
   'role': 'ConsolidatedBalanceSheets'}])

In [68]:
doc = Document.load_all(FACTS_JSON)
doc.tree('ConsolidatedBalanceSheets')

{'us-gaap:Assets': {'us-gaap:InvestmentsAndOtherNoncurrentAssets': {'us-gaap:OtherIntangibleAssetsNet': {},
   'us-gaap:OtherAssetsNoncurrent': {},
   'us-gaap:OperatingLeaseRightOfUseAsset': {},
   'us-gaap:Goodwill': {}},
  'us-gaap:PropertyPlantAndEquipmentNet': {},
  'us-gaap:AssetsCurrent': {'us-gaap:CashAndCashEquivalentsAtCarryingValue': {},
   'us-gaap:AccountsNotesAndLoansReceivableNetCurrent': {},
   'us-gaap:InventoryNet': {},
   'us-gaap:CommodityContractAssetCurrent': {},
   'us-gaap:OtherAssetsCurrent': {}}},
 'us-gaap:LiabilitiesAndStockholdersEquity': {'us-gaap:Liabilities': {'us-gaap:LiabilitiesCurrent': {'us-gaap:LinesOfCreditCurrent': {},
    'ande:AccountsPayableTradeandOtherCurrent': {},
    'us-gaap:ContractWithCustomerLiabilityCurrent': {},
    'us-gaap:DerivativeLiabilitiesCurrent': {},
    'us-gaap:AccruedLiabilitiesCurrent': {},
    'us-gaap:LongTermDebtCurrent': {}},
   'us-gaap:LongTermDebtNoncurrent': {},
   'us-gaap:OperatingLeaseLiabilityNoncurrent': {},
   'us-gaap:OtherLiabilitiesNoncurrent': {}},
  'us-gaap:StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest': {'us-gaap:StockholdersEquity': {'us-gaap:CommonStockValue': {},
    'us-gaap:PreferredStockValue': {},
    'us-gaap:AdditionalPaidInCapitalCommonStock': {},
    'us-gaap:TreasuryStockValue': {},
    'us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax': {},
    'us-gaap:RetainedEarningsAccumulatedDeficit': {}},
   'us-gaap:MinorityInterest': {}},
  'us-gaap:CommitmentsAndContingencies': {}}}

In [70]:
doc = Document.load_all(FACTS_JSON)
doc.expand(concept = 'us-gaap:Assets',
           role_short = 'ConsolidatedBalanceSheets',
           period_end = doc.filing.period_end)

,concept,depth,weight_path,value,label
0,us-gaap:Assets,0,1.0,3712832.0,Assets
1,us-gaap:InvestmentsAndOtherNoncurrentAssets,1,1.0,396923.0,Investments and Other Noncurrent Assets
2,us-gaap:OtherIntangibleAssetsNet,2,1.0,63510.0,"Other Intangible Assets, Net"
3,us-gaap:OtherAssetsNoncurrent,2,1.0,96765.0,"Other Assets, Noncurrent"
4,us-gaap:OperatingLeaseRightOfUseAsset,2,1.0,108792.0,"Operating Lease, Right-of-Use Asset"
5,us-gaap:Goodwill,2,1.0,127856.0,Goodwill
6,us-gaap:PropertyPlantAndEquipmentNet,1,1.0,939500.0,"Property, Plant and Equipment, Net"
7,us-gaap:AssetsCurrent,1,1.0,2376409.0,"Assets, Current"
8,us-gaap:CashAndCashEquivalentsAtCarryingValue,2,1.0,98283.0,Cash and Cash Equivalent
9,us-gaap:AccountsNotesAndLoansReceivableNetCurrent,2,1.0,652472.0,"Accounts and Financing Receivable, after Allow..."
10,us-gaap:InventoryNet,2,1.0,1365121.0,"Inventory, Net"
11,us-gaap:CommodityContractAssetCurrent,2,1.0,135466.0,"Commodity Contract Asset, Current"
12,us-gaap:OtherAssetsCurrent,2,1.0,125067.0,"Other Assets, Current"

---
## 7 - Calc verification

`doc.verify(role_short=None, period_end=None, tolerance=0.0)` checks whether the reported subtotals are arithmetically consistent with their children.

Returns a DataFrame with columns: `parent`, `expected`, `actual`, `diff`, `status`, `role`.

Status values:
- `"match"` - exact (or within tolerance)
- `"rounding"` - small diff <= tolerance (only when tolerance > 0)
- `"mismatch"` - diff > tolerance
- `"missing_children"` - at least one child fact is absent for this period
- `"missing_parent"` - parent fact absent (expected is still computed)

Defaults to `doc.filing.period_end` if `period_end` is not passed. Default tolerance is **strict** (0.0).

> **Try:** `doc.verify()` to see all roles, then narrow with `role_short=`. Re-run with `tolerance=1.0` to suppress filer rounding.

In [71]:
# Your code here
doc = Document.load_all(FACTS_JSON)
doc.verify()

,parent,expected,actual,diff,status,role
0,us-gaap:OtherComprehensiveIncomeLossNetOfTax,NaN,-1248.0,NaN,missing_children,AccumulatedOtherComprehensiveIncomeLossDetails
1,us-gaap:BusinessCombinationConsiderationTransf...,NaN,NaN,NaN,missing_children,BusinessAcquisitionPurchasePriceAllocationDetails
2,us-gaap:BusinessCombinationRecognizedIdentifia...,NaN,NaN,NaN,missing_children,BusinessAcquisitionPurchasePriceAllocationDetails
3,us-gaap:BusinessCombinationRecognizedIdentifia...,NaN,NaN,NaN,missing_children,BusinessAcquisitionPurchasePriceAllocationDetails
4,us-gaap:BusinessCombinationRecognizedIdentifia...,NaN,NaN,NaN,missing_children,BusinessAcquisitionPurchasePriceAllocationDetails
5,us-gaap:Assets,3712832.0,3712832.0,0.0,match,ConsolidatedBalanceSheets
6,us-gaap:AssetsCurrent,2376409.0,2376409.0,0.0,match,ConsolidatedBalanceSheets
7,us-gaap:InvestmentsAndOtherNoncurrentAssets,396923.0,396923.0,0.0,match,ConsolidatedBalanceSheets
8,us-gaap:Liabilities,2422597.0,2422597.0,0.0,match,ConsolidatedBalanceSheets
9,us-gaap:LiabilitiesAndStockholdersEquity,NaN,3712832.0,NaN,missing_children,ConsolidatedBalanceSheets
10,us-gaap:LiabilitiesCurrent,1686397.0,1686397.0,0.0,match,ConsolidatedBalanceSheets
11,us-gaap:StockholdersEquity,NaN,1244779.0,NaN,missing_children,ConsolidatedBalanceSheets
12,us-gaap:StockholdersEquityIncludingPortionAttr...,1290235.0,1290235.0,0.0,match,ConsolidatedBalanceSheets
13,us-gaap:CashCashEquivalentsRestrictedCashAndRe...,-463488.0,-463488.0,0.0,match,ConsolidatedStatementsofCashFlows
14,us-gaap:NetCashProvidedByUsedInFinancingActivi...,-447148.0,-447148.0,0.0,match,ConsolidatedStatementsofCashFlows
15,us-gaap:NetCashProvidedByUsedInInvestingActivi...,NaN,-195315.0,NaN,missing_children,ConsolidatedStatementsofCashFlows
16,us-gaap:NetCashProvidedByUsedInOperatingActivi...,176998.0,176998.0,0.0,match,ConsolidatedStatementsofCashFlows
17,us-gaap:ComprehensiveIncomeNetOfTax,94187.0,94187.0,0.0,match,ConsolidatedStatementsofComprehensiveIncome
18,us-gaap:ComprehensiveIncomeNetOfTaxAttributabl...,23866.0,23866.0,0.0,match,ConsolidatedStatementsofComprehensiveIncome
19,us-gaap:ComprehensiveIncomeNetOfTaxIncludingPo...,118053.0,118053.0,0.0,match,ConsolidatedStatementsofComprehensiveIncome
20,us-gaap:OtherComprehensiveIncomeLossNetOfTax,-1248.0,-1248.0,0.0,match,ConsolidatedStatementsofComprehensiveIncome
21,us-gaap:GrossProfit,713651.0,713651.0,0.0,match,ConsolidatedStatementsofOperations
22,us-gaap:IncomeLossFromContinuingOperationsBefo...,141469.0,141469.0,0.0,match,ConsolidatedStatementsofOperations
23,us-gaap:NetIncomeLoss,95713.0,95713.0,0.0,match,ConsolidatedStatementsofOperations
24,us-gaap:ProfitLoss,119301.0,119301.0,0.0,match,ConsolidatedStatementsofOperations
25,ande:DerivativeAssetFairValueAmountOffsetAgain...,NaN,NaN,NaN,missing_children,DerivativesCurrentandNoncurrentDerivativeAsset...
26,ande:DerivativeLiabilityFairValueAmountNotOffs...,NaN,NaN,NaN,missing_children,DerivativesCurrentandNoncurrentDerivativeAsset...
27,us-gaap:DerivativeFairValueAmountOffsetAgainst...,NaN,NaN,NaN,missing_children,DerivativesCurrentandNoncurrentDerivativeAsset...
28,us-gaap:DerivativeFairValueOfDerivativeAssetAm...,46193.0,46193.0,0.0,match,DerivativesFairValueofCommodityDerivativeswith...
29,us-gaap:IncomeLossFromContinuingOperations,95713.0,95713.0,0.0,match,EarningsPerShareDetails
30,us-gaap:WeightedAverageNumberOfDilutedSharesOu...,34337.0,34337.0,0.0,match,EarningsPerShareDetails
31,ande:FairValueAssetsAndLiabilitiesMeasuredOnRe...,-6045.0,-6045.0,0.0,match,FairValueMeasurementsAssetsandLiabilitiesMeasu...
32,us-gaap:FiniteLivedIntangibleAssetsNet,63510.0,63510.0,0.0,match,GoodwillandOtherIntangibleAssetsIntangibleAsse...
33,us-gaap:DeferredIncomeTaxLiabilities,60143.0,60143.0,0.0,match,IncomeTaxesComponentsofDeferredTaxAssetsandLia...
34,us-gaap:DeferredTaxAssetsGross,85737.0,85737.0,0.0,match,IncomeTaxesComponentsofDeferredTaxAssetsandLia...
35,us-gaap:DeferredTaxAssetsLiabilitiesNet,16426.0,16426.0,0.0,match,IncomeTaxesComponentsofDeferredTaxAssetsandLia...
36,us-gaap:DeferredTaxAssetsNet,76569.0,76569.0,0.0,match,IncomeTaxesComponentsofDeferredTaxAssetsandLia...
37,us-gaap:DeferredTaxLiabilities,-16426.0,NaN,NaN,missing_parent,IncomeTaxesComponentsofDeferredTaxAssetsandLia...
38,us-gaap:EffectiveIncomeTaxRateContinuingOperat...,NaN,15.7,NaN,missing_children,IncomeTaxesEffectiveIncomeTaxReconciliationDet...
39,us-gaap:IncomeTaxExpenseBenefit,NaN,22168.0,NaN,missing_children,IncomeTaxesEffectiveIncomeTaxReconciliationDet...
40,us-gaap:IncomeLossFromContinuingOperationsBefo...,141469.0,141469.0,0.0,match,IncomeTaxesIncomeLossBeforeIncomeTaxesfromCont...
41,us-gaap:CurrentIncomeTaxExpenseBenefit,30828.0,30828.0,0.0,match,IncomeTaxesIncomeTaxProvisionDetails
42,us-gaap:DeferredIncomeTaxExpenseBenefit,-8660.0,-8660.0,0.0,match,IncomeTaxesIncomeTaxProvisionDetails
43,us-gaap:IncomeTaxExpenseBenefit,22168.0,22168.0,0.0,match,IncomeTaxesIncomeTaxProvisionDetails
44,us-gaap:IncomeTaxesPaidNet,16247.0,16247.0,0.0,match,IncomeTaxesScheduleofIncomeTaxesPaidDetails
45,us-gaap:InventoryNet,1365121.0,1365121.0,0.0,match,InventoriesDetails
46,us-gaap:LeaseCost,NaN,47338.0,NaN,missing_children,LeasesComponentsofLeaseCostDetails
47,us-gaap:FinanceLeaseLiabilityPaymentsDue,11091.0,11091.0,0.0,match,LeasesMaturityAnalysisofLeaseLiabilitiesDetails
48,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDue,144917.0,144917.0,0.0,match,LeasesMaturityAnalysisofLeaseLiabilitiesDetails
49,us-gaap:FinanceLeaseLiabilityPaymentsDue,11091.0,11091.0,0.0,match,LeasesMaturityAnalysisofLeaseLiabilitiesDetails_1
50,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDue,144917.0,144917.0,0.0,match,LeasesMaturityAnalysisofLeaseLiabilitiesDetails_1
51,ande:LeaseLiability,108222.0,108222.0,0.0,match,LeasesSummaryofAmountsRecognizedinCondensedCon...
52,ande:RightofUseAsset,130051.0,130051.0,0.0,match,LeasesSummaryofAmountsRecognizedinCondensedCon...
53,us-gaap:FinanceLeaseLiability,9596.0,9596.0,0.0,match,LeasesSummaryofAmountsRecognizedinCondensedCon...
54,us-gaap:OperatingLeaseLiability,98626.0,98626.0,0.0,match,LeasesSummaryofAmountsRecognizedinCondensedCon...
55,us-gaap:NonoperatingIncomeExpense,NaN,78340.0,NaN,missing_children,OtherIncomeNetItemsinOtherIncomeDetails
56,us-gaap:PropertyPlantAndEquipmentGross,1887412.0,1887412.0,0.0,match,PropertyPlantandEquipmentDetails
57,us-gaap:PropertyPlantAndEquipmentNet,939500.0,939500.0,0.0,match,PropertyPlantandEquipmentDetails

---
## 8 - Rendering a statement

`doc.render_statement(role_short, period_end, print=False)` reconstructs a financial statement as indented text, using the **presentation** linkbase for structure and the **calc** linkbase for +/- signs. Labels are resolved if `labs` is attached.

Layout:
```
<Statement title> - period ending YYYY-MM-DD (in millions USD)

  <Section header>
    <Subtotal>                                       123,456
      + <Leaf concept>                                12,345
      - <Leaf concept>                               (12,345)
```

Pass `print=True` to write directly to stdout (cleaner in notebooks).

> **Try:** pick a `role_short` from `doc.pres.role_definitions`, then call `doc.render_statement(role_short, doc.filing.period_end, print=True)`.

In [7]:
# Your code here

doc.render_statement("CONSOLIDATEDBALANCESHEETS", doc.filing.period_end, True)

CONSOLIDATED BALANCE SHEETS — period ending 2025-09-27 (in millions USD)

    Statement of Financial Position [Abstract]
      ASSETS:
        Current assets:
        + Cash and cash equivalents                                  35,934
        + Marketable securities                                      18,763
        + Accounts receivable, net                                   39,777
        + Vendor non-trade receivables                               33,180
        + Inventories                                                 5,718
        + Other current assets                                       14,585
          Total current assets                                      147,957
        Non-current assets:
        + Marketable securities                                      77,723
        + Property, plant and equipment, net                         49,834
        + Other non-current assets                                   83,727
          Total non-current assets                                  211,284
        Total assets                                                359,241
      LIABILITIES AND SHAREHOLDERS’ EQUITY:
        Current liabilities:
        + Accounts payable                                           69,860
        + Other current liabilities                                  66,387
        + Deferred revenue                                            9,055
        + Commercial paper                                            7,979
        + Term debt                                                  12,350
          Total current liabilities                                 165,631
        Non-current liabilities:
        + Term debt                                                  78,328
        + Other non-current liabilities                              41,549
          Total non-current liabilities                             119,877
        Total liabilities                                           285,508
      + Commitments and contingencies  [no value]
        Common stock, shares outstanding (in shares)             14,773,260
        Common stock, shares issued (in shares)                  14,773,260
        Shareholders’ equity:
        + Common stock and additional paid-in capital, $0.00001 par value: 50,400,000 shares authorized; 14,773,260 and 15,116,786 shares issued and outstanding, respectively           93,568
        + Accumulated deficit                                      (14,264)
        + Accumulated other comprehensive loss                      (5,571)
          Total shareholders’ equity                                 73,733
        Total liabilities and shareholders’ equity                  359,241

'CONSOLIDATED BALANCE SHEETS — period ending 2025-09-27 (in millions USD)\n\n    Statement of Financial Position [Abstract]\n      ASSETS:\n        Current assets:\n        + Cash and cash equivalents                                  35,934\n        + Marketable securities                                      18,763\n        + Accounts receivable, net                                   39,777\n        + Vendor non-trade receivables                               33,180\n        + Inventories                                                 5,718\n        + Other current assets                                       14,585\n          Total current assets                                      147,957\n        Non-current assets:\n        + Marketable securities                                      77,723\n        + Property, plant and equipment, net                         49,834\n        + Other non-current assets                                   83,727\n          Total non-current assets                                  211,284\n        Total assets                                                359,241\n      LIABILITIES AND SHAREHOLDERS’ EQUITY:\n        Current liabilities:\n        + Accounts payable                                           69,860\n        + Other current liabilities                                  66,387\n        + Deferred revenue                                            9,055\n        + Commercial paper                                            7,979\n        + Term debt                                                  12,350\n          Total current liabilities                                 165,631\n        Non-current liabilities:\n        + Term debt                                                  78,328\n        + Other non-current liabilities                              41,549\n          Total non-current liabilities                             119,877\n        Total liabilities                                           285,508\n      + Commitments and contingencies  [no value]\n        Common stock, shares outstanding (in shares)             14,773,260\n        Common stock, shares issued (in shares)                  14,773,260\n        Shareholders’ equity:\n        + Common stock and additional paid-in capital, $0.00001 par value: 50,400,000 shares authorized; 14,773,260 and 15,116,786 shares issued and outstanding, respectively           93,568\n        + Accumulated deficit                                      (14,264)\n        + Accumulated other comprehensive loss                      (5,571)\n          Total shareholders’ equity                                 73,733\n        Total liabilities and shareholders’ equity                  359,241\n'

---
## 9 - Linkbase containers (raw access)

Beyond the high-level methods, you can access the raw linkbase objects directly.

### Labels - `doc.labs`
- `doc.labs.entries` -> `list[LabelEntry]` (each has `.concept`, `.label`, `.role`, `.lang`)
- `doc.labs.get(concept, preferred_label=None)` -> `str | None` - resolves the best human-readable label for a concept

### Presentation - `doc.pres`
- `doc.pres.arcs` -> `list[PresArc]` (each has `.role`, `.role_short`, `.role_definition`, `.parent`, `.child`, `.order`, `.preferred_label`)
- `doc.pres.role_definitions` -> `dict[role_short, label]`

### Calculations - `doc.calc`
- `doc.calc.arcs` -> `list[CalcArc]` (each has `.role`, `.role_short`, `.parent`, `.child`, `.weight`, `.order`)
- `doc.calc.role_definitions` -> `dict[role_short, label]`

### Definitions - `doc.defs`
- `doc.defs.arcs` -> `list[DefArc]` (dimensional hypercube relationships)

> **Try:** print `doc.labs.get("us-gaap:Assets")`, list `doc.pres.role_definitions`, inspect a few raw arcs.

In [ ]:
# Your code here

---
## 10 - Round-trip serialisation

`doc.to_dict()` produces the JSON-compatible dict (facts payload only - linkbases excluded by design). `Document.from_dict(d)` is the inverse.

Useful for:
- Writing a filtered subset back to a new `.facts.json`
- Passing a Document to another process via JSON
- Debugging: confirm the dict round-trips cleanly

> **Try:** `d = doc.to_dict()`, then `doc2 = Document.from_dict(d)` and verify `len(doc2.facts) == len(doc.facts)`.

In [ ]:
# Your code here